@WeatherAPI.API_HostAddress = http://localhost:5000

###Current Weather By City
GET {{WeatherAPI.API_HostAddress}}/current/by-city?cityName=miami
Accept: application/json

###Current Weather By Location
GET {{WeatherAPI.API_HostAddress}}/current?lon=-99.9167&lat=21
Accept: application/json

###Forecast By City
GET {{WeatherAPI.API_HostAddress}}/forecast/by-city?cityName=miami
Accept: application/json

###Forecast By Location
GET {{WeatherAPI.API_HostAddress}}/forecast?lon=-99.9167&lat=21
Accept: application/json
